version: 2

jobs:
  test_app:
    docker:
      - image: circleci/python:3.6.3-jessie
        environment:
          SECRET_KEY: my_precious
          APP_SETTINGS: testing
          DATABASE_TEST_URL: postgresql://postgres:@localhost/metagenscope_test
          MONGODB_TEST_HOST: mongodb://localhost/metagenscope_test
      - image: metagenscope/postgres:0afd77cd
        auth:
          username: $DOCKER_ID
          password: $DOCKER_PASSWORD
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
      - image: circleci/mongo

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Lint app
          command: |
            . venv/bin/activate
            make lint

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Provision database
          command: |
            . venv/bin/activate
            python manage.py recreate_db

      - run:
          name: Run application tests
          command: |
            . venv/bin/activate
            python manage.py cov

      - store_artifacts:
          path: htmlcov
          destination: test-reports

workflows:
  version: 2

  app_pipeline:
    jobs:
      - test_app
